Update CI for numeric messages as well

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -46,3 +46,25 @@ jobs:
           echo "FAIL"
           exit 1
         fi
+    - name: Check short capcode numeric correctness
+      run: |
+        cd demos
+        hash1=$(printf "1234567:12345" | ./encode_file -n | md5sum | awk '{print $1}')
+        hash2=$(md5sum ../tests/7digit_numeric_output.bin | awk '{print $1}')
+        if [ "$hash1" = "$hash2" ]; then
+          echo "OK"
+        else
+          echo "FAIL"
+          exit 1
+        fi
+    - name: Check long capcode numeric correctness
+      run: |
+        cd demos
+        hash1=$(printf "123456789:987654321" | ./encode_file -n | md5sum | awk '{print $1}')
+        hash2=$(md5sum ../tests/9digit_numeric_output.bin | awk '{print $1}')
+        if [ "$hash1" = "$hash2" ]; then
+          echo "OK"
+        else
+          echo "FAIL"
+          exit 1
+        fi
